/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AjoutRdv (void);
GtkWidget* create_supprimer_RDV (void);
GtkWidget* create_CRENEAUX (void);
GtkWidget* create_HISTORIQUE_rv (void);
GtkWidget* create_ajout_donneurs (void);
GtkWidget* create_supprimer_donneurs (void);
GtkWidget* create_affichier_rv_donneurs (void);
GtkWidget* create_ajouter_des_dons (void);
GtkWidget* create_supprimer_don (void);
GtkWidget* create_qqt_de_sang (void);
GtkWidget* create_type_rare (void);
GtkWidget* create_demande_de_poche_de_sang (void);
GtkWidget* create_supprime_ets (void);
GtkWidget* create_affichage_ets (void);
GtkWidget* create_type_de_sang__ (void);
GtkWidget* create_modifier_les_donn__s_utilisateur (void);
GtkWidget* create_supprimer_utilisateur (void);
GtkWidget* create_affichage_utilisateur (void);
GtkWidget* create_login (void);
GtkWidget* create_gestionEtablissement (void);
GtkWidget* create_supprimer_ets (void);
GtkWidget* create_ets_par_region (void);
GtkWidget* create_window4 (void);
GtkWidget* create_confirmerSupprimerRdv (void);
GtkWidget* create_ajout_Avec_Sucsess (void);
GtkWidget* create_echec (void);
GtkWidget* create_aceuil (void);
GtkWidget* create_window_donneur (void);
